[package]
name = "evosim-core"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getrandom = { version = "0.2.3", features = ["js"] }
rand = { version = "0.8.4"}